theme: minima
title: Skills of a Bioengineer
author: Kamangu S Maeti
description: This is is a detailed description of the complete technical skill set of the author obtained over his experience an engineer across different domains.
